src/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('new/', views.new_account, name='new'),
    path('edit/', views.edit_account, name='edit'),
    path('profile/', views.my_account, name='me'),
    path('profile/<pk>/', views.UserInfoView.as_view(), name='view'),
    path('profile/<pk>/blog/', views.UserBlogInfoView.as_view(), name='view_blog'),
    path('login/', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'template_name': 'accounts/logout.html'}, name='logout'),
]

src/blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('post/new/', views.NewPostView.as_view(), name='post_new'),
    path('post/<pk>/edit/', views.EditPostView.as_view(), name='post_edit'),
    path('post/<pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('', views.PostListView.as_view(), name='post_list'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from blog.models import Post
from sites.models import Site
from time import time
post_dict = {
        'queryset': Post.objects.all(),
            'date_field': 'published_date'
}
sites_dict = {
    'queryset': Site.objects.all(),
}
sitemaps = {
        'blog': GenericSitemap(post_dict, priority=0.6),
        'home': GenericSitemap(sites_dict, priority=0.7),
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('search/', include('search.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('about/', include('about.urls')),
    path('danny/', include('birthday.urls')),
    path('mail/', include('mail.urls')),
    path('contact/', include('contact.urls')),
    path('', include('home.urls')),
]

src/accounts/models.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.db import models

class UserProfile(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    bio = models.TextField(max_length=500, null=True)

src/accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control'
                }),
            'password': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'password',
                })
            }

src/accounts/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from accounts.models import UserProfile
from django.views import generic
from home.views import CustomView
from blog.models import Post
from django.contrib.auth.decorators import login_required


def new_account(request):
    return HttpResponse("new account")

def edit_account(request):
    return HttpResponse("edit account")

@login_required
def my_account(request):
    return redirect('accounts:view', pk=request.user.pk)

class UserInfoView(CustomView, generic.DetailView):
    model = UserProfile
    context_object_name = 'userprof'
    template_name = 'accounts/profile.html'

    def get_more_context(self):
        return {'title': "profile", 'page': "info"}


class UserBlogInfoView(CustomView, generic.ListView):
    model = UserProfile
    context_object_name = 'posts'
    template_name = 'accounts/profile.html'

    def get_queryset(self):
        qs = Post.objects.all().filter(author_id=self.kwargs['pk'])
        return qs
    def get_more_context(self):
        return {'title': "profile", 'page': "blog", 'userprof': UserProfile.objects.filter(pk=self.kwargs['pk']).first()}

src/accounts/templates/accounts/login.html
{% extends 'home/base.html' %}

{% block content %}
<h1>Login</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

src/accounts/templates/accounts/logout.html
{% extends 'home/base.html' %}

{% block content %}
<div class="container-fluid">
    <h1>Bye</h1>
    <p>You have just logged out. If this was a mistake click <a href="{% url 'accounts:login' %}">here</a> to log back in.</p>
</div>
{% endblock %}

src/accounts/templates/accounts/profile.html
{% extends 'home/base.html' %}

{% block content %}
<ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link{% if page == 'info' %} active{% endif %}" href="{% if page != 'info' %}{% url 'accounts:view' userprof.pk %}{% else %}#{% endif %}">Info</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if page == 'blog' %} active{% endif %}" href="{% if page != 'blog' %}{% url 'accounts:view_blog' userprof.pk %}{% else %}#{% endif %}">Blog</a>
  </li>
</ul>

<div class="container-fluid">
<br>
{% if page == 'info' %}
{% load gravatar %}

<div class="row">
        <div class="col-sm-2">
		<img src="{% gravatar_url userprof.email 300 %}" class="rounded-circle img-fluid" />
	</div>
        <div class="col-sm-10">
{% if userprof.first_name %}{{ userprof.first_name }} {% if userprof.last_name %}{{ userprof.last_name }}{% endif %}<br>{% endif %}
{% if userprof.username %}@{{ userprof.username }}<br>{% endif %}
{% if userprof.last_login %}Last Seen: {{ userprof.last_login }}<br>{% endif %}
{% if userprof.bio %}<blockquote><p>{{ userprof.bio }}</p></blockquote>{% endif %}
	</div>
</div>
{% else %}
{% for post in posts %}
<br>
{% include 'blog/post.html' %}
</div>
{% endfor %}

{% endif %}
</div>
{% endblock %}